### ISSUE TITLE
Topology should default to `none`

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#115]
Currently the topology options in the operator are `standalone` and `leader/follower`, we need to add an option of no topology. The default option in Habitat is `none` and the operator should default to that as well, which means:
> the difference between standalone and none is that none will never update itself

See further discussion for this [here](https://github.com/kinvolk/habitat-operator/pull/114#issuecomment-338117140).

**Comment by asymmetric** [comment]
But also consider https://github.com/kinvolk/habitat-operator/pull/114#issuecomment-338136458. i.e. do we really need `none`?

**Comment by zeenix** [comment]
@asymmetric maybe someday soon the difference between standalone and none will make a difference for operator as well? I guess best just map it exactly already?

**Comment by asymmetric** [comment]
Yeah, no strong feelings against it, 👍.

**Comment by zeenix** [comment]
Cool, so we need to remember to also add the 'none' topology to the k8s exporter cli after we add this.

**Comment by asymmetric** [comment]
Protip: create an issue for that and add it to the board.

**Comment by zeenix** [comment]
We we were informed by Habitat folks, there is no "none" topology and default is "standalone".
