### ISSUE TITLE
Promoting a Habitat application to the another channel

### ISSUE THREAD

**Issue by nhlfr** [kinvolk/habitat-operator#127]
User may want to change the channel (idea of channels is described in #126). In example, if some application is in the `staging` channel, user may want to promote it to `production` after the tests are done.

Our idea is to introduce a new CRD type called `HabitatPromote` which will contain the following information:

- name of `Habitat` object to promote
- old channel name
- new channel name
- bool value which determines whether the deployment with old channel should be removed

**Comment by asymmetric** [comment]
Closing for now. We will revisit this if needed.
