### ISSUE TITLE
Limit the number of docker images we use in the examples

### ISSUE THREAD

**Issue by krnowak** [kinvolk/habitat-operator#165]
Currently we use 5 of them:

- kinvolk/postgresql-hab
- kinvolk/bindgo-hab
- kinvolk/nodejs-hab
- kinvolk/consul-hab
- kinvolk/nginx-hab

The first two are used in tests. I wonder if we could replace them with fewer images and smaller. (postgresql image is 600 mb).

That should make it a bit less painful when updating the images to use newer habitat version.

**Comment by krnowak** [comment]
There's also kinvolk/habitat-operator, but it's out of question.

**Comment by asymmetric** [comment]
`s/postgresql|nginx|consul/redis`
