### ISSUE TITLE
Upgrade dependencies to latest patch version

### ISSUE THREAD

**Issue by asymmetric** [kinvolk/habitat-operator#175]
1.9.2 of [https://github.com/kubernetes/apimachinery]() and company have been released.

**Comment by asymmetric** [comment]
I tried [upgrading](https://github.com/kinvolk/habitat-operator/compare/asymmetric/upgrade-patch) to the latest pach, `1.9.2`, but somehow dep seems to think that's not possible, and only upgrades to `1.9.1`.

No idea if that's correct, or if dep is misbehaving.

**Comment by asymmetric** [comment]
@LiliC Should we pin to the `kubernetes-1.9.0` ta for dependencies, or the `release-1.9` one? I'm confused by [this](https://github.com/kubernetes/client-go/#kubernetes-tags) and how it interacts with `client-go` dependencies.

**Comment by asymmetric** [comment]
OK, found [this](http://blog.kubernetes.io/2018/01/introducing-client-go-version-6.html) about the `kubernetes-vx.y.z` tags:

> These tags have limited test coverage, but can be used by early adopters of client-go and the other libraries. Moreover, they help to vendor the correct version of k8s.io/api and k8s.io/apimachinery. Note that we only create a v6.0.3-like semantic versioning tag on k8s.io/client-go. The corresponding tag for k8s.io/api and k8s.io/apimachinery is kubernetes-1.9.3.

> Also note that only these tags correspond to tested releases of Kubernetes. If you depend on the release branch, e.g., release-1.9, your client is running on unreleased Kubernetes code.

**Comment by LiliC** [comment]
@asymmetric I would just stick to `v0.6.0` and not worry about supporting `1.9.x` versions. Unless you have a very good reason for that?

**Comment by LiliC** [comment]
> Also, did you mean v6.0.0? And when you say "not worry about supporting 1.9.x" you mean sticking to 1.9.0?

Yes I would stick to `1.9.0` and client-go `v6.0.0`.

**Comment by asymmetric** [comment]
Thanks. I think that's the recommended approach anyway (matching minor versions), although I'm not 100% sure.
