### ISSUE TITLE
Introduce workqueue

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#26]
To make sure individual events don't interfere with each other, upstream Kubernetes suggestion is for controllers to implement a workqueue. 

More info can be found [here.](https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md)

**Comment by asymmetric** [comment]
I would argue this only becomes a problem when we start running event handlers in parallel.

At the moment, we only run one, so there's no real need for a queue.
