### ISSUE TITLE
Explore integration of Open Service Broker API

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#36]
One way to implement the Open Service Broker API we can explore the [Kubernetes service catalog](https://github.com/kubernetes-incubator/service-catalog) which is currently in the Kubernetes incubator. 

Prerequisites for the service catalog to work we would need:
- Kubernetes cluster with cluster DNS enabled
- Helm charts
- Handle RBAC roles

**Comment by LiliC** [comment]
This is to sum up my thoughts from the meeting:

My general idea would be to have a catalog of stateful applications images packaged with Habitat (e.g. databases). They would pre-configured using the `default.toml` file and pushed to a public registry. User would have a catalog of images, and request a service, which is where our custom broker comes in. It would create a Kubernetes manifest file using the Habitat image from the requested catalog item, type would be ServiceGroup which is how our Habitat Operator can identify it. Broker would then deploy it to the Kubernetes cluster. Habitat Operator would then take over managing that application. 

cc @tashimi @fnichol Can you also write down the ideas you had for the Open Service Broker API in general. And also if you could leave some suggestion on the above idea. Thanks!

**Comment by tashimi** [comment]
Some ideas I had for Open Service Broker API: 

- have ability to build my stateless application and have it managed on kubernetes, and then stand up my persistent data tier on vms/baremetal, and connect the different tiers via the API 
- determine if there need to be two rings, one for k8s, one for non-k8s managed workloads 
- figure out how to do binds/exports between habitat managed services in different management tiers

**Comment by tashimi** [comment]
Also, speaking of Helm charts, would it be possible to export a habitat package as a helm chart? I also want to add the ability for habitat to scan a repo, detect a helm chart, and "do the right thing" as far as fill in habitat defaults in the *.toml's correctly based on your helm chart.

**Comment by asymmetric** [comment]
@LiliC can this exploration issue be closed? Are there any other more specific ones it makes sense to create and add to the board?

**Comment by LiliC** [comment]
@asymmetric good catch, will close and open other larger issues for both brokers.
