### ISSUE TITLE
Rename CRD ServiceGroup

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#39]
Current name `ServiceGroup` conflicts with concept of a `group` in Habitat, as well as concept of a `Service` in Kubernetes, we need to come up with a better name for CRD.

List of ideas:
- [HabitatService](https://github.com/kinvolk/habitat-operator/pull/30)
- Habitat

**Comment by asymmetric** [comment]
What changed since we decided to close #30?

**Comment by LiliC** [comment]
We decided to close that PR as we couldn't come up with anything better then `ServiceGroup`, but we agreed that `ServiceGroup` is not the best name from what I remember? 

In one of our last meetings I believe we sort of agreed on `Habitat`, but I wanted your input before changing everything to that, so I opened the issue to not forget and also to discuss/collect ideas.

**Comment by asymmetric** [comment]
A pro of using "Habitat" would be that we would follow the logic of other operators:

* PrometheusOperator -> Prometheus
* ReplicaSetController -> ReplicaSet
* ...

**Comment by LiliC** [comment]
Closed by https://github.com/kinvolk/habitat-operator/pull/85
