### ISSUE TITLE
Create e2e tests

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#54]
Create e2e tests.

**Comment by LiliC** [comment]
My initial conclusions on the tests we can do right now. So we do not every time when we make changes to our codebase, need to spin up our operator manually and create each example I would suggest starting with E2E tests.

E2e tests would be located in the `tests` directory and would cover scenarios such as resource deletion, checking whether we still have IP of a pod that is running, etc. At first we can run them locally against our `minikube`, maybe later on have a setup for those to be run automatically.

When we decide on our projects architecture we can start on focusing more on unit tests.

@asymmetric wdyt?

**Comment by asymmetric** [comment]
I'm not sure I understand what the conclusions are :)

Is it that you'd like to focus on E2E tests  instead of unit testing the `writeIP` method? That's totally fine by me.

I would still keep this issue around for unit testing that method, and add a description in this issue of the 4 things we discussed yesterday.

**Comment by LiliC** [comment]
Added the suggestions, feel free to edit, if you can think of something else, or if I misunderstood.

**Comment by asymmetric** [comment]
Is this issue about E2E testing or unit testing? I think that could be reflected in the title/description.

**Comment by LiliC** [comment]
Would you prefer if we keep this issue just for unit tests? And we create a separate one for e2e? I am fine with that.

**Comment by asymmetric** [comment]
I'm just not sure what this issue is about, but I'm fine with you choosing that :)
