### ISSUE TITLE
Run E2E tests automatically

### ISSUE THREAD

**Issue by asymmetric** [kinvolk/habitat-operator#76]
This issue is to explore ways in which we can make running our E2E tests part of the CI process.

* Parallelizing Travis jobs using the [build matrix](https://docs.travis-ci.com/user/speeding-up-the-build/)
* Using the `-j` flag in `make`
* Using a [cron job](https://docs.travis-ci.com/user/cron-jobs/) to periodically run the E2E tests on master
* Using a custom bash script that only runs the E2E tests on master
* Only running the E2E tests in the job that tests the PR merge commit (e.g. checking `$TRAVIS_PULL_REQUEST` in a bash script)

**Comment by LiliC** [comment]
Two options I see for for running our e2e tests on Travis CI: 
- We could use `minikube` for this, there is a flag to use no drivers `--vm-driver=none`. That should bypass the problem with having to get virtual machines running on top of Travis CI. Using `minikube` gives us the option to reproduce the failed tests locally and therefor fix them much easily.
- There is also [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster)
