### ISSUE TITLE
Running a hab Service Group inside of k8s

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#8]
This is about running a Service Group as a collection of manually created pods, and confirming that the supervisors in the SG are able to talk to one another, and, for example, elect a leader.

Two types of pods will have to be crated, since we're still relying on the current `--peer` mechanism, and therefore we run supervisors with different flags.

Checklist
---

- [x] Pods can fetch from the internet
- [x] Leader election succeeds

**Comment by asymmetric** [comment]
Closing as both checkboxes ticked. Also, this is too broad, I don't think it's very useful.
