### ISSUE TITLE
Rename Config field

### ISSUE THREAD

**Issue by asymmetric** [kinvolk/habitat-operator#95]
See https://github.com/kinvolk/habitat-operator/pull/94#discussion_r140207694

**Comment by LiliC** [comment]
Going by your comment from the PR:
> I think we should rename the Config field by the way. It's a name,whereas intuitively I'd think it's an actual config. So either ConfigName, or Config.Name would work I think.

To stay consistent with other fields, for example we already have `RingSecretName`, think it maybe should be called `ConfigSecretName`. Or we can rename that to `RingSecret.Name` and then go with `ConfigSecret.Name`?

What do you think, I am open for other suggestions.

**Comment by asymmetric** [comment]
If there are no other keys, I'd say `ConfigSecretName` is fine for now.
