### ISSUE TITLE
RBAC rules for Operator

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#99]
Create [role based access control](https://kubernetes.io/docs/admin/authorization/rbac/) rules for the Habitat operator.

Kubernetes RBAC has been promoted to v1 in Kubernetes `1.8` and major Kubernetes distributions turn it on by default which means, that the Kubernetes apiserver will deny all access to its APIs by default. RBAC is there to enable access to those APIs. 

The Habitat operator makes heavy use of the Kubernetes APIs, therefore we need to document the required RBAC roles, in order for users to run the Habitat operator in a secure manner.

**Comment by asymmetric** [comment]
Don't forget to add to board ;)
